version: '3'

services:
  govideo:
    image: govideo
    container_name: govideo 
    restart: on-failure
    ports:
      - 30163:30163
    environment:
      - TOPICNAME=videodisplay
      - KAFKAPORT=kafka1:19095
      - GROUPNAME=govideo
      - DISPLAYPORT=:30163
      - NODEPORT=:30163
      - FRAMEINTERVAL=10ms
    volumes:
      - /tmp/govideo:/tmp  
    networks:
      - zookeeper_dockerNet 
        # To ensure that the containers in different docker-compose files communicate with each other, we place them on the same network. The complete network name is 'zookeeper_dockerNet'. It is derived by joining the name of the folder from which the network originates (i.e., zookeeper) and the name of the network (i.e., dockerNet).
      
networks:
  zookeeper_dockerNet:
    external: true #Label the other docker-compose network as an external network to the current docker-compose file

